// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy89QAz0olJUV8ZCHu8vq1dG-KKkPVfSc',
    appId: '1:341283228802:web:eea93f11beaa5abc89b89b',
    messagingSenderId: '341283228802',
    projectId: 'mnotes',
    authDomain: 'mnotes-fc5ae.firebaseapp.com',
    storageBucket: 'mnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Vj0zMOGdPKlOpoJD1Cy-rsmV8-dYZEQ',
    appId: '1:341283228802:android:7b0d2f653934086889b89b',
    messagingSenderId: '341283228802',
    projectId: 'mnotes',
    storageBucket: 'mnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBND6Rn7mICNt5Tzx1XVvEOotCexcrLDQ',
    appId: '1:341283228802:ios:a332488c38e253ce89b89b',
    messagingSenderId: '341283228802',
    projectId: 'mnotes',
    storageBucket: 'mnotes.appspot.com',
    iosClientId: '341283228802-4h3435uin30pf7q143mjmad2c95v2a3i.apps.googleusercontent.com',
    iosBundleId: 'com.abhikb.app',
  );
}
